"""
build_vectorstore.py

Builds a FAISS vector index from courses_dataset.jsonl (generated by
generate_dataset.py) using Ollama embeddings (nomic-embed-text).

The resulting index is saved to ./faiss_index, which is the same folder
app.py loads on startup (INDEX_DIR / "faiss_index" by default).

Resumable: progress is checkpointed after every batch, so if Ollama
crashes (e.g. "connection refused" on a large dataset), simply re-run
this script and it will continue from where it left off.

USAGE:
    1. Make sure Ollama is running:        ollama serve
    2. Pull the embedding model (once):    ollama pull nomic-embed-text
    3. Generate the dataset (one-time):    python generate_dataset.py
    4. Build the index:                    python build_vectorstore.py
       If it crashes partway through, just run it again — it resumes.
"""

import json
import os
import sys
import time

from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS
from langchain_ollama import OllamaEmbeddings

# ── Config ────────────────────────────────────────────────────────────────────
# Keep these in sync with app.py (which reads the same env vars / defaults).
DATASET_PATH = os.environ.get("DATASET_PATH", "courses_dataset.jsonl")
INDEX_DIR    = os.environ.get("INDEX_DIR", "faiss_index")
EMBED_MODEL  = os.environ.get("EMBED_MODEL", "nomic-embed-text")

PROGRESS_FILE = os.path.join(INDEX_DIR, "build_progress.json")

# Small batches are slower but far less likely to crash the Ollama runner
# on memory-constrained machines. 100,000 records / 64 = ~1,560 batches.
BATCH_SIZE = 100

MAX_RETRIES_PER_BATCH = 5
RETRY_BACKOFF_SECONDS = [5, 15, 30, 60, 120]  # waits between retries
# ─────────────────────────────────────────────────────────────────────────────


# ── Dataset loading & document conversion ───────────────────────────────────

def record_to_document(rec: dict) -> Document:
    """Must match record_to_document in app.py exactly, so the index
    produced here is compatible with what app.py expects to retrieve."""
    focus_text = ", ".join(rec.get("focus", []))
    content = (
        f"Course: {rec['course']}\n"
        f"University: {rec['university']}\n"
        f"Focus areas: {focus_text}"
    )
    return Document(
        page_content=content,
        metadata={
            "university": rec["university"],
            "course": rec["course"],
            "focus": rec.get("focus", []),
        },
    )


def load_records(dataset_path):
    if not os.path.exists(dataset_path):
        sys.exit(
            f"Dataset file '{dataset_path}' not found. "
            f"Run `python generate_dataset.py` first to create it."
        )

    records = []
    if dataset_path.endswith(".jsonl"):
        with open(dataset_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
    else:
        with open(dataset_path, "r", encoding="utf-8") as f:
            records = json.load(f)

    if not records:
        sys.exit(f"'{dataset_path}' contains no records.")

    print(f"Loaded {len(records):,} course record(s) from '{dataset_path}'.")
    return records


# ── Progress checkpointing ──────────────────────────────────────────────────

def load_progress():
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"records_done": 0, "total_records": None}


def save_progress(records_done, total_records):
    os.makedirs(INDEX_DIR, exist_ok=True)
    with open(PROGRESS_FILE, "w", encoding="utf-8") as f:
        json.dump({"records_done": records_done, "total_records": total_records}, f)


def clear_progress():
    if os.path.exists(PROGRESS_FILE):
        os.remove(PROGRESS_FILE)


# ── Embeddings & index building ─────────────────────────────────────────────

def make_embeddings():
    return OllamaEmbeddings(model=EMBED_MODEL)


def check_ollama_alive(embeddings):
    """Quick connectivity check. Exits with a helpful message if unreachable."""
    try:
        embeddings.embed_query("connectivity check")
    except Exception as e:
        sys.exit(
            f"Could not reach Ollama model '{EMBED_MODEL}'.\n"
            f"  - Is Ollama running? Try: ollama serve\n"
            f"  - Is the model pulled?  Try: ollama pull {EMBED_MODEL}\n"
            f"  - On Windows, check Task Manager for a crashed 'ollama' "
            f"process and restart it if needed.\n"
            f"Original error: {e}"
        )


def embed_batch_with_retry(vectorstore, batch_docs, embeddings):
    """
    Embed and add a batch of documents, retrying with backoff on failure.
    Returns (vectorstore, embeddings) — embeddings may be re-created on retry
    in case the client's connection/state went stale after an Ollama crash.
    """
    for attempt in range(MAX_RETRIES_PER_BATCH):
        try:
            if vectorstore is None:
                vectorstore = FAISS.from_documents(batch_docs, embeddings)
            else:
                vectorstore.add_documents(batch_docs)
            return vectorstore, embeddings
        except Exception as e:
            if attempt == MAX_RETRIES_PER_BATCH - 1:
                raise
            wait = RETRY_BACKOFF_SECONDS[min(attempt, len(RETRY_BACKOFF_SECONDS) - 1)]
            print(f"  -> embedding error: {e}")
            print(f"  -> retrying in {wait}s (attempt {attempt + 1}/{MAX_RETRIES_PER_BATCH})...")
            time.sleep(wait)
            embeddings = make_embeddings()


def build_index(records, embeddings):
    total = len(records)
    progress = load_progress()

    if progress["total_records"] not in (None, total):
        print(
            "WARNING: the number of records has changed since the last run "
            f"({progress['total_records']} -> {total}). Starting fresh to "
            "avoid an inconsistent index."
        )
        clear_progress()
        progress = {"records_done": 0, "total_records": total}

    records_done = progress["records_done"]

    if records_done >= total:
        print("All records were already embedded in a previous run.")
        return FAISS.load_local(INDEX_DIR, embeddings, allow_dangerous_deserialization=True)

    vectorstore = None
    if records_done > 0:
        print(f"Resuming from checkpoint: {records_done:,}/{total:,} records already done.")
        vectorstore = FAISS.load_local(INDEX_DIR, embeddings, allow_dangerous_deserialization=True)

    for start in range(records_done, total, BATCH_SIZE):
        end = min(start + BATCH_SIZE, total)
        batch_docs = [record_to_document(r) for r in records[start:end]]
        print(f"Embedding records {start + 1:,}-{end:,} of {total:,}...")

        vectorstore, embeddings = embed_batch_with_retry(vectorstore, batch_docs, embeddings)

        # Persist after every batch so a crash never loses more than one
        # batch's worth of work.
        vectorstore.save_local(INDEX_DIR)
        save_progress(end, total)

    return vectorstore


def main():
    print(f"Initialising Ollama embeddings (model='{EMBED_MODEL}')...")
    embeddings = make_embeddings()
    check_ollama_alive(embeddings)

    records = load_records(DATASET_PATH)

    print("Building FAISS index. This can take a while for large datasets...")
    vectorstore = build_index(records, embeddings)

    vectorstore.save_local(INDEX_DIR)
    clear_progress()
    print(f"\nDone! FAISS index saved to '{INDEX_DIR}/' ({len(records):,} records indexed).")


if __name__ == "__main__":
    main()